# Generated by Django 5.0.6 on 2024-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
